batch_size: 4
max_steps: 400
eval_interval: 50
ablation_no_sleep: false
ablation_disable_hippocampus: false
reward_from_correctness: true
amp_enabled: false
amp_dtype: fp16
allow_tf32: false
matmul_precision: high
compile_model: false
compile_mode: reduce-overhead
