slow_lr: 0.000001
wake_base_lr_scale: 0.0
sleep_min_interval: 100
sleep_max_interval: 500
min_sleep_steps: 25
max_sleep_steps: 200
pseudo_rehearsal: false
pseudo_ratio: 0.25
pseudo_source: mixed
pseudo_random_fraction: 0.5
fisher_use_capability_mix: true
refresh:
  kl_threshold: 0.05
  reset_factor: 0.1
